### ISSUE TITLE
How to build a hypergraph with node weights and hyperedge weights?

### ISSUE THREAD

**Issue by mr1ck7** [pnnl/HyperNetX#115] opened 2023-06-26 11:27 UTC
Should I use edge_weight_prop,and node_weight_prop to assign values to edge weights and node weights? I noticed that there is a cell_weigh property, I want to know what cell weight represents

**Comment by bpraggastis** [comment] 2023-07-11 20:37
Cell weight reference edge dependent weights. In general properties can be assigned to nodes and edges of a hypergraph but there might be some data that depends on the incidence pair. For example, take all movies as hyperedges and all actors who play in those movies as nodes. Tom Hanks will belong to Forest Gump and Toy Story. But his role in each of those movies, and the amount of money he made for each of those movies, are distinct. That is what is meant by cell properties - where a cell references the (node,edge) indexed position in the incidence matrix.

**Comment by MCDalvean** [comment] 2023-07-24 13:11
Greetings,

I would like to inquire about weights assigned in HyperNetx.

The following is an extract from my code:

dataframe = pd.read_csv(r'/home........../nodescsv.csv')

H = hnx.Hypergraph(dataframe,edge_col="col1",node_col="col2",cell_weight_col="w")


The problem is that the weights do not seem to have any effect on the hypergraph. When I change the weights in the source dataframe, there is no change in the hypergraph.

Furthermore, when I run hmod.precompute_attributes(H) and run  H.edges, H.nodes and H.d_weights, all 69 nodes in the hypergraph get weight = 1, strength = 69 and H.d_weights = 69.

Any insight you could provide on this issue would be most appreciated.

**Comment by MCDalvean** [comment] 2023-07-26 09:32
Thanks for your reply.
One clarification I should make (I didn't explain the situation well in my previous post):
The dataframe has a column for nodes, a column for edges, and a column for weights. The problem is that both a and b below produce the same graph-

a ) H = hnx.Hypergraph(dataframe,edge_col="col1",node_col="col2",cell_weight_col="w")
b) H = hnx.Hypergraph(dataframe,edge_col="col1",node_col="col2")

I hope this clarifies the issue.

**Comment by brendapraggastis** [comment] 2024-08-08 06:06
@MCDalvean The latest release of HNX should behave as expected. thanks for bringing this to our attention. We did quite a bit of internal surgery and it is much faster and more reliable.

**Closed by brendapraggastis** 2024-08-08 06:06 UTC
Labels: active
